### ISSUE TITLE
需要复制 swagger上的哪里

### ISSUE THREAD

**Issue by abigmiu** [AKclown/js-to-ts#1]
这样直接复制的不行

![image](https://user-images.githubusercontent.com/43983920/201570113-9ad3a0ae-c774-40d8-924e-e9abfa4c5098.png)

**Comment by AKclown** [comment]
是的，目前不支持，我后续加上这种匹配转换

**Comment by AKclown** [comment]
![image](https://user-images.githubusercontent.com/33648653/203920499-5320cd7d-ceb1-424f-b245-0d2933bb145b.png)
我之前只考虑了上面场景，没注意post请求的

**Comment by AKclown** [comment]
我后续看是否能支持你这种格式的

**Comment by AKclown** [comment]
你好！
很抱歉这么久才新增功能。 新增的功能一应该可以满足你的需求。
