### ISSUE TITLE
增加支持curl请求方式且为默认的请求方式

### ISSUE THREAD

**Issue by GeSnowBoy** [AKclown/js-to-ts#14]

**Comment by GeSnowBoy** [comment]
curl请求在浏览器直接就可以copy出来。 粘贴进去就ok了。  现在的填写方式太繁琐

**Comment by AKclown** [comment]
感谢反馈，该需求已经记录，后续会[进行支持](https://github.com/AKclown/js-to-ts/issues/2#issuecomment-1635241338)

**Comment by AKclown** [comment]
![image](https://github.com/AKclown/js-to-ts/assets/33648653/ac16a15f-1860-4270-b463-c43e1c9a6cb8)

Hi,GeSnowBoy. 已支持curl，我没有做大规模测试，目前我的mock链接是可以的
