### ISSUE TITLE
随便公司一个一个接口通不了

### ISSUE THREAD

**Issue by lxc482113948** [AKclown/js-to-ts#15]
就是公司的接口有请求头部有token 有appid在咱的插件里都设置了还是请求不了请问这个是有bug还是我方法不对
<img width="701" alt="image" src="https://github.com/AKclown/js-to-ts/assets/71561182/08de623b-88b0-4bf3-87e0-6c91d5e9dcb6">

**Comment by AKclown** [comment]
貌似是你们请求不允许跨域了。你可以在`vscode -> help -> Toggle Developer Tools`打开vscode控制台查看信息
![image](https://github.com/AKclown/js-to-ts/assets/33648653/e7b5a042-dc2d-460f-bbe8-a099d3f96e6e)

**Comment by AKclown** [comment]
可以使用v0.6.0的curl功能，看看是否能解决跨域问题，感谢

**Comment by AKclown** [comment]
预计下一个版本可以解决该问题。
处理方案为: 将webview的请求时机，下发到Node层去处理
