### ISSUE TITLE
Error: Timeout awaiting 'request' for 2000ms , timeout configuration item needs to be added.

### ISSUE THREAD

**Issue by Camusama** [AKclown/js-to-ts#19]
<img width="364" alt="image" src="https://github.com/AKclown/js-to-ts/assets/36040009/369f1bf6-6ed3-4180-9c57-1b724d5512e1">

**Comment by AKclown** [comment]
这个错误提示`curl`请求超时（及HTTP请求超时），你可以用bash控制台尝试一下是否也是如此呢？ 或者可能提供一下crul文本，我这边尝试一下

**Comment by AKclown** [comment]
hi, camusama,刚仔细看标题，[已添加对应配置，并且超时默认改为6000ms](https://github.com/AKclown/js-to-ts/pull/20#issue-1819868951).请更新0.6.2
