### ISSUE TITLE
When the prefix is empty, it will be converted to the string "false".

### ISSUE THREAD

**Issue by Camusama** [AKclown/js-to-ts#21]
<img width="1386" alt="image" src="https://github.com/AKclown/js-to-ts/assets/36040009/ac00d87c-d872-4e06-ae1f-5db5c344efd6">

Furthermore, the plugin is excellent. I will go and give it a positive review.

**Comment by AKclown** [comment]
Thank you for your approval, the prefix empty string is false in v0.6.3 version has been fixed

**Comment by AKclown** [comment]
Thank you for your approval, Issue fixed, v0.6.3
