### ISSUE TITLE
插件无法使用，swagger.to.typescript

### ISSUE THREAD

**Issue by xinyuxia** [AKclown/js-to-ts#3]
插件安装后，使用swagger.to.typescript命令，报错提示：command 'swagger.to.typescript.convert' not found

**Comment by AKclown** [comment]
Hi, xinyuxia
我这里是正常的，我的vscode版本为`v1.66.2`。插件版本为`v0.3.3`。系统为`win11`。方便的话，麻烦提供一下这些基础信息
![212](https://user-images.githubusercontent.com/33648653/235065634-15eb5354-5699-4f6c-80b8-f511b6929ed7.gif)

**Comment by xinyuxia** [comment]
vscode版本: 1.77.3 (user setup)
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No

系统：window10专业版&nbsp;
插件：v0.3.3







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月28日(星期五) 中午1:55
收件人: ***@***.***&gt;; 
抄送: "sun s ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AKclown/swagger-to-typescript] 插件无法使用，swagger.to.typescript (Issue #3)





 
Hi, xinyuxia
 我这里是正常的，我的vscode版本为v1.66.2。插件版本为v0.3.3。系统为win11。方便的话，麻烦能提供一些这些基础信息吗？

**Comment by AKclown** [comment]
Hi, xinyuxia。
更新一下包为0.3.4修复该问题。 感谢你的反馈
