### ISSUE TITLE
请问大神，在编辑页右键菜单里面，点击菜单，怎么打开左侧自己的插件弹窗呢？

### ISSUE THREAD

**Issue by Promise-W** [AKclown/js-to-ts#30]
大神，如题。就是在子菜单里面新增一个功能，可以打开左侧插件弹窗
![image](https://github.com/AKclown/js-to-ts/assets/7625487/623d6f58-2780-400b-8e23-f47bbf7b7de3)

**Comment by AKclown** [comment]
嗨咯`Promise-W`, 这是一个问题还是一个插件优化请求呢？ 
通过配置`workbench.view.extension.你的activitybar对应得id`即可创建打开`activitybar`得快捷操作
![image](https://github.com/AKclown/js-to-ts/assets/33648653/0cf6cf49-242f-498f-921c-4f47be34b4bb)
如果你想在右击菜单也存在，在如下加多一个{...}
![image](https://github.com/AKclown/js-to-ts/assets/33648653/13701831-dd27-4943-a7a1-843aa0369a89)
